import { Exercise, WorkoutDay, WorkoutDayExercise, WorkoutPhase, WorkoutPlan } from '../types';

// ─── Exercise Library ────────────────────────────────────────────────────────

export const EXERCISES: Record<string, Exercise> = {
  // UPPER PUSH
  pushup: {
    id: 'pushup',
    name: 'Push-Up',
    muscle_group: 'chest',
    description: 'Classic bodyweight chest and tricep builder.',
    instructions: [
      'Start in a high plank with hands shoulder-width apart',
      'Lower your chest until it almost touches the floor',
      'Keep your core tight and body in a straight line',
      'Push back up explosively',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 60,
    posture_support: true,
    equipment: [],
    difficulty: 'beginner',
  },
  db_shoulder_press: {
    id: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscle_group: 'shoulders',
    description: 'Seated or standing overhead press for shoulder mass.',
    instructions: [
      'Hold dumbbells at shoulder height, palms facing forward',
      'Press them overhead until arms are nearly locked',
      'Lower with control back to shoulder height',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 60,
    posture_support: true,
    equipment: ['dumbbells'],
    difficulty: 'beginner',
  },
  lateral_raise: {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    muscle_group: 'shoulders',
    description: 'Isolation move for lateral deltoids.',
    instructions: [
      'Stand with dumbbells at your sides',
      'Raise arms out to sides until parallel to the floor',
      'Lead with your elbows, not your hands',
      'Lower slowly',
    ],
    default_sets: 3,
    default_reps: 15,
    rest_sec: 45,
    posture_support: false,
    equipment: ['dumbbells'],
    difficulty: 'beginner',
  },
  tricep_dip: {
    id: 'tricep_dip',
    name: 'Tricep Dip',
    muscle_group: 'arms',
    description: 'Bodyweight tricep and chest exercise.',
    instructions: [
      'Place hands on a sturdy chair or bench, fingers forward',
      'Lower your body by bending your elbows to 90°',
      'Keep your back close to the chair',
      'Push back up',
    ],
    default_sets: 3,
    default_reps: 10,
    rest_sec: 60,
    posture_support: false,
    equipment: ['chair'],
    difficulty: 'beginner',
  },
  wall_plank: {
    id: 'wall_plank',
    name: 'Wall Plank Hold',
    muscle_group: 'core',
    description: 'Core stabilization exercise.',
    instructions: [
      'Place forearms against a wall at chest height',
      'Step back until body is at a diagonal angle',
      'Hold tight core and straight line from head to heels',
    ],
    default_sets: 3,
    default_reps: 1,
    default_duration_sec: 30,
    rest_sec: 45,
    posture_support: true,
    equipment: [],
    difficulty: 'beginner',
  },
  db_bench_press: {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    muscle_group: 'chest',
    description: 'Horizontal pressing for full chest development.',
    instructions: [
      'Lie on a bench, hold dumbbells at chest level',
      'Press them up until arms are extended',
      'Lower with control, feel the stretch in your chest',
    ],
    default_sets: 4,
    default_reps: 10,
    rest_sec: 90,
    posture_support: true,
    equipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
  },
  arnold_press: {
    id: 'arnold_press',
    name: 'Arnold Press',
    muscle_group: 'shoulders',
    description: 'Rotational shoulder press hitting all three delt heads.',
    instructions: [
      'Start with dumbbells in front of you, palms facing you',
      'Press up while rotating palms away',
      'At the top, palms face forward',
      'Reverse the rotation on the way down',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 60,
    posture_support: false,
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
  },
  // LOWER BODY
  bodyweight_squat: {
    id: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    muscle_group: 'legs',
    description: 'Foundation lower body movement.',
    instructions: [
      'Stand with feet shoulder-width apart, toes slightly out',
      'Push hips back and bend knees',
      'Lower until thighs are parallel to the floor',
      'Drive through your heels to stand up',
    ],
    default_sets: 3,
    default_reps: 15,
    rest_sec: 60,
    posture_support: true,
    equipment: [],
    difficulty: 'beginner',
  },
  reverse_lunge: {
    id: 'reverse_lunge',
    name: 'Reverse Lunge',
    muscle_group: 'legs',
    description: 'Unilateral leg movement improving balance and strength.',
    instructions: [
      'Stand tall, step one foot back',
      'Lower your back knee toward the floor',
      'Front thigh should be parallel to floor',
      'Drive through front heel to return',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 60,
    posture_support: true,
    equipment: [],
    difficulty: 'beginner',
  },
  glute_bridge: {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    muscle_group: 'legs',
    description: 'Posterior chain activation targeting glutes and hamstrings.',
    instructions: [
      'Lie on your back, knees bent, feet flat on floor',
      'Drive your hips up by squeezing your glutes',
      'Hold at the top for 1 second',
      'Lower with control',
    ],
    default_sets: 3,
    default_reps: 15,
    rest_sec: 45,
    posture_support: false,
    equipment: [],
    difficulty: 'beginner',
  },
  calf_raise: {
    id: 'calf_raise',
    name: 'Calf Raise',
    muscle_group: 'legs',
    description: 'Isolation exercise for gastrocnemius and soleus.',
    instructions: [
      'Stand at the edge of a step or flat ground',
      'Rise onto your toes as high as possible',
      'Squeeze at the top',
      'Lower slowly below starting position',
    ],
    default_sets: 3,
    default_reps: 20,
    rest_sec: 45,
    posture_support: false,
    equipment: [],
    difficulty: 'beginner',
  },
  dead_bug: {
    id: 'dead_bug',
    name: 'Dead Bug',
    muscle_group: 'core',
    description: 'Anti-extension core stability exercise.',
    instructions: [
      'Lie on your back with arms pointing to ceiling',
      'Knees bent at 90° in the air',
      'Slowly extend opposite arm and leg toward the floor',
      'Return and repeat on the other side',
    ],
    default_sets: 3,
    default_reps: 10,
    rest_sec: 45,
    posture_support: false,
    equipment: [],
    difficulty: 'beginner',
  },
  romanian_deadlift: {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    muscle_group: 'legs',
    description: 'Hip hinge movement targeting hamstrings and glutes.',
    instructions: [
      'Hold dumbbells in front of your thighs',
      'Hinge at the hips, pushing them back',
      'Lower the weights along your legs, keeping back neutral',
      'Feel the stretch in your hamstrings',
      'Drive hips forward to return',
    ],
    default_sets: 4,
    default_reps: 10,
    rest_sec: 90,
    posture_support: true,
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    muscle_group: 'legs',
    description: 'Advanced unilateral quad and glute builder.',
    instructions: [
      'Place rear foot on a bench behind you',
      'Lower your back knee toward the floor',
      'Keep front shin vertical',
      'Drive through your front heel',
    ],
    default_sets: 3,
    default_reps: 10,
    rest_sec: 90,
    posture_support: true,
    equipment: ['bench'],
    difficulty: 'intermediate',
  },
  barbell_squat: {
    id: 'barbell_squat',
    name: 'Barbell Back Squat',
    muscle_group: 'legs',
    description: 'King of all leg exercises for overall lower body mass.',
    instructions: [
      'Bar rests on upper traps, not neck',
      'Feet shoulder-width apart, toes out 30°',
      'Brace your core, take a breath, sit back and down',
      'Hit parallel or below',
      'Drive through heels, keeping chest up',
    ],
    default_sets: 4,
    default_reps: 8,
    rest_sec: 120,
    posture_support: true,
    equipment: ['barbell', 'squat rack'],
    difficulty: 'advanced',
  },
  // UPPER PULL
  resistance_band_row: {
    id: 'resistance_band_row',
    name: 'Resistance Band Row',
    muscle_group: 'back',
    description: 'Beginner-friendly back exercise using a resistance band.',
    instructions: [
      'Anchor band at waist height',
      'Pull the band toward your torso, elbows tucking in',
      'Squeeze shoulder blades at the end',
      'Return with control',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 60,
    posture_support: false,
    equipment: ['resistance band'],
    difficulty: 'beginner',
  },
  db_bent_row: {
    id: 'db_bent_row',
    name: 'Dumbbell Bent-Over Row',
    muscle_group: 'back',
    description: 'Compound back builder for thickness.',
    instructions: [
      'Hinge at the hips with a neutral spine',
      'Pull dumbbells toward your hips, elbows close to body',
      'Squeeze at the top',
      'Lower with control',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 60,
    posture_support: true,
    equipment: ['dumbbells'],
    difficulty: 'beginner',
  },
  face_pull: {
    id: 'face_pull',
    name: 'Face Pull',
    muscle_group: 'shoulders',
    description: 'Rear delt and rotator cuff health exercise.',
    instructions: [
      'Anchor a resistance band at face height',
      'Pull toward your face, elbows high and wide',
      'Externally rotate wrists at the end',
      'Return with control',
    ],
    default_sets: 3,
    default_reps: 15,
    rest_sec: 45,
    posture_support: false,
    equipment: ['resistance band'],
    difficulty: 'beginner',
  },
  bicep_curl: {
    id: 'bicep_curl',
    name: 'Dumbbell Bicep Curl',
    muscle_group: 'arms',
    description: 'Classic bicep isolation.',
    instructions: [
      'Stand with dumbbells at your sides',
      'Curl the weights up, keeping elbows pinned',
      'Squeeze at the top',
      'Lower fully',
    ],
    default_sets: 3,
    default_reps: 12,
    rest_sec: 45,
    posture_support: false,
    equipment: ['dumbbells'],
    difficulty: 'beginner',
  },
  plank: {
    id: 'plank',
    name: 'Plank',
    muscle_group: 'core',
    description: 'Full body core stabilization.',
    instructions: [
      'Forearms on the ground, elbows under shoulders',
      'Body in a straight line from head to heels',
      'Brace your core — squeeze everything',
      'Breathe normally',
    ],
    default_sets: 3,
    default_reps: 1,
    default_duration_sec: 40,
    rest_sec: 45,
    posture_support: true,
    equipment: [],
    difficulty: 'beginner',
  },
  pullup: {
    id: 'pullup',
    name: 'Pull-Up',
    muscle_group: 'back',
    description: 'Upper body pull king for lat width.',
    instructions: [
      'Grip a bar slightly wider than shoulders',
      'Hang with full arm extension',
      'Pull your chest to the bar, leading with elbows',
      'Lower with control',
    ],
    default_sets: 4,
    default_reps: 8,
    rest_sec: 90,
    posture_support: false,
    equipment: ['pull-up bar'],
    difficulty: 'intermediate',
  },
  deadlift: {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    muscle_group: 'back',
    description: 'Total body compound movement, builds everything.',
    instructions: [
      'Bar over mid-foot, grip just outside legs',
      'Hinge down, chest up, back flat',
      'Brace hard, drive feet into the floor',
      'Lock out hips at the top',
      'Lower the bar with control',
    ],
    default_sets: 4,
    default_reps: 6,
    rest_sec: 180,
    posture_support: true,
    equipment: ['barbell'],
    difficulty: 'advanced',
  },
  // CARDIO / HIIT
  burpee: {
    id: 'burpee',
    name: 'Burpee',
    muscle_group: 'cardio',
    description: 'Full body HIIT staple for maximum calorie burn.',
    instructions: [
      'From standing, drop hands to the floor',
      'Jump feet back to plank',
      'Perform a push-up (optional)',
      'Jump feet forward, then jump up with arms overhead',
    ],
    default_sets: 8,
    default_reps: 1,
    default_duration_sec: 20,
    rest_sec: 10,
    posture_support: false,
    equipment: [],
    difficulty: 'intermediate',
  },
  jump_squat: {
    id: 'jump_squat',
    name: 'Jump Squat',
    muscle_group: 'legs',
    description: 'Explosive plyometric for power and calorie burn.',
    instructions: [
      'Squat down to parallel',
      'Explode upward, jumping off the floor',
      'Land softly, immediately descend into the next squat',
    ],
    default_sets: 8,
    default_reps: 1,
    default_duration_sec: 20,
    rest_sec: 10,
    posture_support: false,
    equipment: [],
    difficulty: 'intermediate',
  },
  mountain_climber: {
    id: 'mountain_climber',
    name: 'Mountain Climber',
    muscle_group: 'core',
    description: 'Dynamic core + cardio exercise.',
    instructions: [
      'Start in a high plank position',
      'Drive one knee toward your chest, then switch rapidly',
      'Keep hips level, core tight',
    ],
    default_sets: 8,
    default_reps: 1,
    default_duration_sec: 20,
    rest_sec: 10,
    posture_support: false,
    equipment: [],
    difficulty: 'intermediate',
  },
  // YOGA
  surya_namaskar: {
    id: 'surya_namaskar',
    name: 'Surya Namaskar (Sun Salutation)',
    muscle_group: 'yoga',
    description: 'Complete yoga sequence warming the entire body.',
    instructions: [
      'Mountain Pose → Arms Overhead',
      'Forward Fold → Halfway Lift',
      'Step back to Plank → Chaturanga',
      'Upward Dog → Downward Dog',
      'Step forward → Rise back to Mountain',
    ],
    default_sets: 5,
    default_reps: 1,
    rest_sec: 30,
    posture_support: true,
    equipment: ['yoga mat'],
    difficulty: 'beginner',
  },
  warrior_1: {
    id: 'warrior_1',
    name: 'Warrior I (Virabhadrasana I)',
    muscle_group: 'yoga',
    description: 'Hip flexor stretch with shoulder opening.',
    instructions: [
      'Step one foot forward, back foot at 45°',
      'Bend front knee over ankle',
      'Rise arms overhead, gaze upward',
      'Square hips toward the front',
      'Hold 5 breaths each side',
    ],
    default_sets: 1,
    default_reps: 1,
    default_duration_sec: 60,
    rest_sec: 15,
    posture_support: true,
    equipment: ['yoga mat'],
    difficulty: 'beginner',
  },
  warrior_2: {
    id: 'warrior_2',
    name: 'Warrior II (Virabhadrasana II)',
    muscle_group: 'yoga',
    description: 'Hip-opening standing pose building leg strength.',
    instructions: [
      'Step feet wide apart, front foot forward',
      'Bend front knee, thigh parallel to floor',
      'Arms extend out to sides, gaze over front fingers',
      'Open hips to the side',
      'Hold 5 breaths each side',
    ],
    default_sets: 1,
    default_reps: 1,
    default_duration_sec: 60,
    rest_sec: 15,
    posture_support: true,
    equipment: ['yoga mat'],
    difficulty: 'beginner',
  },
  pigeon_pose: {
    id: 'pigeon_pose',
    name: 'Pigeon Pose',
    muscle_group: 'yoga',
    description: 'Deep hip opener releasing piriformis and hip flexors.',
    instructions: [
      'From Downward Dog, bring one knee forward behind your wrist',
      'Extend back leg straight behind you',
      'Lower hips toward the floor',
      'Fold forward over your front leg',
      'Hold 10 breaths each side',
    ],
    default_sets: 1,
    default_reps: 1,
    default_duration_sec: 90,
    rest_sec: 15,
    posture_support: true,
    equipment: ['yoga mat'],
    difficulty: 'intermediate',
  },
  box_breathing: {
    id: 'box_breathing',
    name: 'Box Breathing (Pranayama)',
    muscle_group: 'meditation',
    description: 'Breathing technique for nervous system regulation.',
    instructions: [
      'Sit comfortably, spine tall',
      'Inhale for 4 counts',
      'Hold for 4 counts',
      'Exhale for 4 counts',
      'Hold empty for 4 counts',
      'Repeat for 10 cycles',
    ],
    default_sets: 1,
    default_reps: 10,
    default_duration_sec: 600,
    rest_sec: 0,
    posture_support: false,
    equipment: [],
    difficulty: 'beginner',
  },
  body_scan_meditation: {
    id: 'body_scan_meditation',
    name: 'Body Scan Meditation',
    muscle_group: 'meditation',
    description: 'Progressive relaxation and mindfulness practice.',
    instructions: [
      'Lie in Savasana or sit comfortably',
      'Close your eyes and breathe naturally',
      'Bring attention to your feet — notice any sensation',
      'Slowly move awareness up through each body part',
      'End at the crown of your head',
    ],
    default_sets: 1,
    default_reps: 1,
    default_duration_sec: 600,
    rest_sec: 0,
    posture_support: false,
    equipment: [],
    difficulty: 'beginner',
  },
  // ZUMBA
  zumba_routine: {
    id: 'zumba_routine',
    name: 'Zumba Dance Routine',
    muscle_group: 'zumba',
    description: 'High-energy Latin dance workout for cardio and joy.',
    instructions: [
      'Follow the video or instructor routine',
      'Move with the music — don\'t worry about perfection',
      'Keep moving even if you miss a step',
      'Increase intensity with larger arm movements',
    ],
    default_sets: 1,
    default_reps: 1,
    default_duration_sec: 1800,
    rest_sec: 0,
    posture_support: false,
    equipment: [],
    difficulty: 'beginner',
  },

  // ── WARM-UP EXERCISES ──────────────────────────────────────────────────────
  wu_jumping_jacks: {
    id: 'wu_jumping_jacks',
    name: 'Jumping Jacks',
    muscle_group: 'cardio',
    description: 'Full-body warm-up that elevates heart rate and loosens every joint.',
    instructions: [
      'Stand with feet together and arms at your sides',
      'Jump feet out wide while swinging arms overhead',
      'Jump back to starting position with control',
      'Maintain a comfortable pace — this is warm-up, not max effort',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 45, rest_sec: 10,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=jumping+jacks+warmup+tutorial',
    video_type: 'youtube',
  },
  wu_arm_circles: {
    id: 'wu_arm_circles',
    name: 'Arm Circles',
    muscle_group: 'shoulders',
    description: 'Mobilises the shoulder joint before upper-body work.',
    instructions: [
      'Stand with arms stretched straight out to the sides',
      'Make small forward circles, gradually increasing the size',
      'After 15 seconds, reverse direction',
      'Keep shoulders down and neck relaxed',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=arm+circles+shoulder+warmup+exercise',
    video_type: 'youtube',
  },
  wu_leg_swings: {
    id: 'wu_leg_swings',
    name: 'Leg Swings',
    muscle_group: 'legs',
    description: 'Dynamic hip-flexor and hamstring warm-up using pendulum momentum.',
    instructions: [
      'Hold a wall or stable surface for balance',
      'Swing one leg forward and back in a controlled pendulum',
      'Keep the movement smooth — momentum does the work',
      'Switch legs halfway through',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=leg+swings+hip+flexor+warmup',
    video_type: 'youtube',
  },
  wu_hip_circles: {
    id: 'wu_hip_circles',
    name: 'Hip Circles',
    muscle_group: 'legs',
    description: 'Opens the hip joint and improves range of motion for squats and lunges.',
    instructions: [
      'Stand with feet shoulder-width apart, hands on hips',
      'Slowly rotate your hips in wide circles clockwise',
      'Do 5 clockwise, then 5 counter-clockwise',
      'Move slowly — feel the stretch at end range',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=hip+circles+mobility+warmup',
    video_type: 'youtube',
  },
  wu_high_knees_march: {
    id: 'wu_high_knees_march',
    name: 'High Knee March',
    muscle_group: 'cardio',
    description: 'Low-impact cardiovascular activation for hips, core, and coordination.',
    instructions: [
      'Stand tall with good posture and a slight core brace',
      'Lift one knee slowly to hip height, then alternate',
      'Swing the opposite arm for balance',
      'Gradually increase your pace over the 30 seconds',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: true, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=high+knee+march+warmup+exercise',
    video_type: 'youtube',
  },
  wu_torso_rotation: {
    id: 'wu_torso_rotation',
    name: 'Standing Torso Rotations',
    muscle_group: 'core',
    description: 'Thoracic spine mobility drill for safer rotational exercises.',
    instructions: [
      'Stand with feet shoulder-width apart, arms extended forward',
      'Rotate your upper body to the right as far as comfortable',
      'Return through centre then rotate left',
      'Keep hips square — move the torso only',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=standing+torso+rotation+warmup+mobility',
    video_type: 'youtube',
  },
  wu_wrist_ankle_circles: {
    id: 'wu_wrist_ankle_circles',
    name: 'Wrist & Ankle Circles',
    muscle_group: 'core',
    description: 'Mobilises the smaller joints often skipped in warm-up.',
    instructions: [
      'Extend one arm and rotate the wrist 10 times each direction',
      'Lift one foot and rotate the ankle 10 times each direction',
      'Repeat on the opposite side',
      'Move with full range of motion, nice and slow',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=wrist+ankle+circles+warmup+mobility',
    video_type: 'youtube',
  },

  // ── COOL-DOWN / STRETCH EXERCISES ─────────────────────────────────────────
  cd_childs_pose: {
    id: 'cd_childs_pose',
    name: "Child's Pose",
    muscle_group: 'yoga',
    description: 'Calming full-back decompression and hip-flexor opener to close any session.',
    instructions: [
      'Kneel and sit hips back toward your heels',
      'Reach arms forward on the floor, forehead resting down',
      'Breathe deeply and let your back gently expand',
      'Walk arms to one side for a lateral stretch, then the other',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 45, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=childs+pose+yoga+cooldown+stretch',
    video_type: 'youtube',
  },
  cd_standing_quad_stretch: {
    id: 'cd_standing_quad_stretch',
    name: 'Standing Quad Stretch',
    muscle_group: 'legs',
    description: 'Lengthens the quadriceps and hip flexor after lower-body or full-body work.',
    instructions: [
      'Stand on one leg; hold a wall for balance if needed',
      'Bend the other knee and hold your foot behind you',
      'Keep knees together and stand tall',
      'Hold 20 seconds, then switch sides',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 45, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=standing+quad+stretch+cooldown',
    video_type: 'youtube',
  },
  cd_hamstring_stretch: {
    id: 'cd_hamstring_stretch',
    name: 'Seated Hamstring Stretch',
    muscle_group: 'legs',
    description: 'Relieves hamstring tension after squats, lunges, and running.',
    instructions: [
      'Sit on the floor with one leg straight in front',
      'Bend the other leg so the foot rests against the inner thigh',
      'Hinge at the hips and reach forward along the straight leg',
      'Keep your back flat — do not round the spine. 20 s each side',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 45, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=seated+hamstring+stretch+cooldown',
    video_type: 'youtube',
  },
  cd_chest_stretch: {
    id: 'cd_chest_stretch',
    name: 'Doorway Chest Stretch',
    muscle_group: 'chest',
    description: 'Counters anterior shoulder rounding after push and bench work.',
    instructions: [
      'Stand in a doorway, place forearms on each side of the frame',
      'Step one foot forward and gently lean through the doorway',
      'Feel the stretch across your chest and front shoulders',
      'Breathe into the stretch — hold without bouncing',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 30, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=doorway+chest+stretch+cooldown+pec',
    video_type: 'youtube',
  },
  cd_shoulder_stretch: {
    id: 'cd_shoulder_stretch',
    name: 'Cross-Body Shoulder Stretch',
    muscle_group: 'shoulders',
    description: 'Releases the rear deltoid and rotator cuff after pulling work.',
    instructions: [
      'Bring one arm straight across your chest at shoulder height',
      'Use the opposite forearm to press it gently toward you',
      'Keep your shoulder down — do not shrug',
      'Hold 20 seconds, then switch arms',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 40, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=cross+body+shoulder+stretch+cooldown',
    video_type: 'youtube',
  },
  cd_spinal_twist: {
    id: 'cd_spinal_twist',
    name: 'Supine Spinal Twist',
    muscle_group: 'core',
    description: 'Decompresses the spine and stretches the IT band, glutes, and obliques.',
    instructions: [
      'Lie on your back with knees bent, feet flat on the floor',
      'Drop both knees to one side and look the opposite way',
      'Keep both shoulders flat on the ground',
      'Hold 20 seconds, then switch sides',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 45, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=supine+spinal+twist+stretch+cooldown',
    video_type: 'youtube',
  },
  cd_cat_cow: {
    id: 'cd_cat_cow',
    name: 'Cat-Cow Stretch',
    muscle_group: 'core',
    description: 'Gentle spinal mobilisation to wind down the nervous system.',
    instructions: [
      'Start on hands and knees — wrists under shoulders, knees under hips',
      'Inhale: drop belly, lift chest and tailbone (Cow)',
      'Exhale: round spine toward ceiling, tuck chin and tailbone (Cat)',
      'Move slowly with your breath for 8–10 full cycles',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 45, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=cat+cow+stretch+yoga+cooldown',
    video_type: 'youtube',
  },
  cd_neck_stretch: {
    id: 'cd_neck_stretch',
    name: 'Neck Side Stretch',
    muscle_group: 'shoulders',
    description: 'Releases upper-trapezius and neck tension built up during any workout.',
    instructions: [
      'Sit or stand tall with relaxed shoulders',
      'Tilt your right ear slowly toward your right shoulder',
      'Optionally, rest your right hand gently on your head for a deeper stretch',
      'Hold 20 seconds, then switch to the left side',
    ],
    default_sets: 1, default_reps: 1, default_duration_sec: 40, rest_sec: 5,
    posture_support: false, equipment: [], difficulty: 'beginner',
    video_url: 'https://www.youtube.com/results?search_query=neck+side+stretch+cooldown+trapezius',
    video_type: 'youtube',
  },
};

// ─── Phase 1 Workout Days (Weeks 1–4) ────────────────────────────────────────

const phase1Days: WorkoutDay[] = [
  {
    id: 'p1_monday',
    day_of_week: 1,
    name: 'Upper Push',
    focus: 'Chest • Shoulders • Triceps',
    muscle_groups: ['chest', 'shoulders', 'arms'],
    full_duration_min: 50,
    express_duration_min: 25,
    micro_duration_min: 10,
    phase: 1,
    notes: 'Focus on form and mind-muscle connection today. The weight doesn\'t matter — the movement does.',
    exercises: [
      { exercise: EXERCISES.pushup, sets: 3, reps: 12, rest_sec: 60, order: 1 },
      { exercise: EXERCISES.db_shoulder_press, sets: 3, reps: 12, rest_sec: 60, order: 2 },
      { exercise: EXERCISES.lateral_raise, sets: 3, reps: 15, rest_sec: 45, order: 3 },
      { exercise: EXERCISES.tricep_dip, sets: 3, reps: 10, rest_sec: 60, order: 4 },
      { exercise: EXERCISES.wall_plank, sets: 3, reps: 1, rest_sec: 45, order: 5 },
    ],
    express_exercises: ['pushup', 'db_shoulder_press', 'tricep_dip'],
    micro_exercises: ['pushup', 'db_shoulder_press', 'plank'],
    desk_exercises: ['wall_plank', 'tricep_dip'],
  },
  {
    id: 'p1_tuesday',
    day_of_week: 2,
    name: 'Zumba + Core + Meditation',
    focus: 'Cardio • Core • Mind',
    muscle_groups: ['zumba', 'core', 'meditation'],
    full_duration_min: 60,
    express_duration_min: 30,
    micro_duration_min: 15,
    phase: 1,
    notes: 'Let the music move you. Zumba re-entry — enjoy it, don\'t judge it.',
    exercises: [
      { exercise: EXERCISES.zumba_routine, sets: 1, reps: 1, rest_sec: 0, order: 1 },
      { exercise: EXERCISES.plank, sets: 3, reps: 1, rest_sec: 45, order: 2 },
      { exercise: EXERCISES.dead_bug, sets: 3, reps: 10, rest_sec: 45, order: 3 },
      { exercise: EXERCISES.box_breathing, sets: 1, reps: 10, rest_sec: 0, order: 4 },
    ],
    express_exercises: ['zumba_routine', 'plank', 'box_breathing'],
    micro_exercises: ['zumba_routine', 'box_breathing'],
    desk_exercises: ['box_breathing'],
  },
  {
    id: 'p1_wednesday',
    day_of_week: 3,
    name: 'Lower Body',
    focus: 'Quads • Hamstrings • Glutes • Calves',
    muscle_groups: ['legs', 'core'],
    full_duration_min: 55,
    express_duration_min: 25,
    micro_duration_min: 10,
    phase: 1,
    notes: 'Strong legs = strong foundation. Every squat fights visceral fat.',
    exercises: [
      { exercise: EXERCISES.bodyweight_squat, sets: 3, reps: 15, rest_sec: 60, order: 1 },
      { exercise: EXERCISES.reverse_lunge, sets: 3, reps: 12, rest_sec: 60, order: 2 },
      { exercise: EXERCISES.glute_bridge, sets: 3, reps: 15, rest_sec: 45, order: 3 },
      { exercise: EXERCISES.calf_raise, sets: 3, reps: 20, rest_sec: 45, order: 4 },
      { exercise: EXERCISES.dead_bug, sets: 3, reps: 10, rest_sec: 45, order: 5 },
    ],
    express_exercises: ['bodyweight_squat', 'reverse_lunge', 'glute_bridge'],
    micro_exercises: ['bodyweight_squat', 'glute_bridge', 'calf_raise'],
    desk_exercises: ['calf_raise', 'bodyweight_squat'],
  },
  {
    id: 'p1_thursday',
    day_of_week: 4,
    name: 'Zone 2 Cardio',
    focus: 'Trail Run • Cycling • Fat Burn',
    muscle_groups: ['cardio'],
    full_duration_min: 45,
    express_duration_min: 25,
    micro_duration_min: 12,
    phase: 1,
    notes: 'Keep HR between 120–140 bpm. This is your fat-burning zone. Enjoy the trail.',
    exercises: [],
    express_exercises: [],
    micro_exercises: [],
    desk_exercises: [],
  },
  {
    id: 'p1_friday',
    day_of_week: 5,
    name: 'Upper Pull + Core',
    focus: 'Back • Biceps • Core',
    muscle_groups: ['back', 'arms', 'core'],
    full_duration_min: 55,
    express_duration_min: 25,
    micro_duration_min: 10,
    phase: 1,
    notes: 'Pull movements balance your push days and protect your shoulders.',
    exercises: [
      { exercise: EXERCISES.resistance_band_row, sets: 3, reps: 12, rest_sec: 60, order: 1 },
      { exercise: EXERCISES.db_bent_row, sets: 3, reps: 12, rest_sec: 60, order: 2 },
      { exercise: EXERCISES.face_pull, sets: 3, reps: 15, rest_sec: 45, order: 3 },
      { exercise: EXERCISES.bicep_curl, sets: 3, reps: 12, rest_sec: 45, order: 4 },
      { exercise: EXERCISES.plank, sets: 3, reps: 1, rest_sec: 45, order: 5 },
    ],
    express_exercises: ['resistance_band_row', 'db_bent_row', 'bicep_curl'],
    micro_exercises: ['db_bent_row', 'face_pull', 'plank'],
    desk_exercises: ['resistance_band_row', 'face_pull'],
  },
  {
    id: 'p1_saturday',
    day_of_week: 6,
    name: 'Yoga + Meditation',
    focus: 'Flexibility • Balance • Mind',
    muscle_groups: ['yoga', 'meditation'],
    full_duration_min: 60,
    express_duration_min: 30,
    micro_duration_min: 15,
    phase: 1,
    notes: 'Yoga is not separate from your fitness — it is the foundation. Breathe.',
    exercises: [
      { exercise: EXERCISES.surya_namaskar, sets: 5, reps: 1, rest_sec: 30, order: 1 },
      { exercise: EXERCISES.warrior_1, sets: 1, reps: 1, rest_sec: 15, order: 2 },
      { exercise: EXERCISES.warrior_2, sets: 1, reps: 1, rest_sec: 15, order: 3 },
      { exercise: EXERCISES.pigeon_pose, sets: 1, reps: 1, rest_sec: 15, order: 4 },
      { exercise: EXERCISES.body_scan_meditation, sets: 1, reps: 1, rest_sec: 0, order: 5 },
    ],
    express_exercises: ['surya_namaskar', 'warrior_2', 'body_scan_meditation'],
    micro_exercises: ['surya_namaskar', 'body_scan_meditation'],
    desk_exercises: ['box_breathing'],
  },
  {
    id: 'p1_sunday',
    day_of_week: 0,
    name: 'Active Recovery',
    focus: 'Walk • Gardening • Meal Prep',
    muscle_groups: ['full_body'],
    full_duration_min: 30,
    express_duration_min: 15,
    micro_duration_min: 10,
    phase: 1,
    notes: 'Rest is part of the plan. Stay active, prep your meals, reflect on the week.',
    exercises: [
      { exercise: EXERCISES.box_breathing, sets: 1, reps: 10, rest_sec: 0, order: 1 },
    ],
    express_exercises: ['box_breathing'],
    micro_exercises: ['box_breathing'],
    desk_exercises: ['box_breathing'],
  },
];

// ─── Phase 2 Workout Days (Weeks 5–8) ────────────────────────────────────────

const phase2Days: WorkoutDay[] = phase1Days.map((day) => {
  if (day.id === 'p1_monday') {
    return {
      ...day,
      id: 'p2_monday',
      phase: 2 as const,
      notes: 'Now we add weight. Progressive overload starts here.',
      exercises: [
        { exercise: EXERCISES.db_bench_press, sets: 4, reps: 10, rest_sec: 90, order: 1 },
        { exercise: EXERCISES.arnold_press, sets: 3, reps: 12, rest_sec: 60, order: 2 },
        { exercise: EXERCISES.lateral_raise, sets: 3, reps: 15, rest_sec: 45, order: 3 },
        { exercise: EXERCISES.tricep_dip, sets: 3, reps: 12, rest_sec: 60, order: 4 },
        { exercise: EXERCISES.plank, sets: 3, reps: 1, rest_sec: 45, order: 5 },
      ],
    };
  }
  if (day.id === 'p1_wednesday') {
    return {
      ...day,
      id: 'p2_wednesday',
      phase: 2 as const,
      notes: 'Add load to your squats and lunges this phase.',
      exercises: [
        { exercise: EXERCISES.romanian_deadlift, sets: 4, reps: 10, rest_sec: 90, order: 1 },
        { exercise: EXERCISES.bulgarian_split_squat, sets: 3, reps: 10, rest_sec: 90, order: 2 },
        { exercise: EXERCISES.glute_bridge, sets: 3, reps: 15, rest_sec: 45, order: 3 },
        { exercise: EXERCISES.calf_raise, sets: 4, reps: 20, rest_sec: 45, order: 4 },
        { exercise: EXERCISES.dead_bug, sets: 3, reps: 12, rest_sec: 45, order: 5 },
      ],
    };
  }
  return { ...day, id: day.id.replace('p1_', 'p2_'), phase: 2 as const };
});

// ─── Phase 3 Workout Days (Weeks 9–16) ───────────────────────────────────────

const phase3Days: WorkoutDay[] = [
  {
    id: 'p3_monday',
    day_of_week: 1,
    name: 'Push Day (Heavy)',
    focus: 'Chest • Shoulders • Triceps — Heavy',
    muscle_groups: ['chest', 'shoulders', 'arms'],
    full_duration_min: 60,
    express_duration_min: 30,
    micro_duration_min: 12,
    phase: 3,
    notes: 'Hypertrophy phase: 4 sets, 8–10 reps. Add 2.5kg from last week if you completed all reps.',
    exercises: [
      { exercise: EXERCISES.db_bench_press, sets: 4, reps: 10, rest_sec: 90, order: 1 },
      { exercise: EXERCISES.arnold_press, sets: 4, reps: 10, rest_sec: 90, order: 2 },
      { exercise: EXERCISES.lateral_raise, sets: 4, reps: 12, rest_sec: 60, order: 3 },
      { exercise: EXERCISES.tricep_dip, sets: 4, reps: 12, rest_sec: 60, order: 4 },
      { exercise: EXERCISES.plank, sets: 3, reps: 1, rest_sec: 45, order: 5 },
    ],
    express_exercises: ['db_bench_press', 'arnold_press', 'tricep_dip'],
    micro_exercises: ['db_bench_press', 'plank'],
    desk_exercises: ['wall_plank'],
  },
  {
    id: 'p3_thursday_hiit',
    day_of_week: 4,
    name: 'HIIT Tabata',
    focus: 'Burpees • Jump Squats • Mountain Climbers',
    muscle_groups: ['cardio', 'full_body'],
    full_duration_min: 30,
    express_duration_min: 20,
    micro_duration_min: 8,
    phase: 3,
    notes: '8 rounds Tabata: 20s work / 10s rest. This is meant to be hard.',
    exercises: [
      { exercise: EXERCISES.burpee, sets: 8, reps: 1, rest_sec: 10, order: 1 },
      { exercise: EXERCISES.jump_squat, sets: 8, reps: 1, rest_sec: 10, order: 2 },
      { exercise: EXERCISES.mountain_climber, sets: 8, reps: 1, rest_sec: 10, order: 3 },
    ],
    express_exercises: ['burpee', 'jump_squat'],
    micro_exercises: ['burpee', 'mountain_climber'],
    desk_exercises: ['mountain_climber'],
  },
];

// ─── Full Workout Plan ────────────────────────────────────────────────────────

export const WORKOUT_PLAN: WorkoutPlan = {
  id: 'fitlife_6month',
  name: 'FitLife 6-Month Transformation',
  description: 'A progressive 6-month plan combining strength training, HIIT, Yoga, Zumba, and Meditation — designed for visceral fat elimination and lean muscle building.',
  duration_weeks: 24,
  phases: [
    {
      phase_number: 1,
      name: 'Foundation & Re-conditioning',
      description: 'Re-awaken muscles, establish movement patterns, begin fat mobilization. Form is everything this phase.',
      weeks_start: 1,
      weeks_end: 4,
      days: phase1Days,
    },
    {
      phase_number: 2,
      name: 'Building Strength + Fat Burn Activation',
      description: 'Introduce dumbbells/barbells. Increase volume and begin progressive overload.',
      weeks_start: 5,
      weeks_end: 8,
      days: phase2Days,
    },
    {
      phase_number: 3,
      name: 'Hypertrophy + HIIT Acceleration',
      description: 'Maximum muscle stimulus combined with HIIT for accelerated fat loss.',
      weeks_start: 9,
      weeks_end: 16,
      days: phase3Days,
    },
    {
      phase_number: 4,
      name: 'Body Recomposition + Lifestyle Lock',
      description: 'Maintenance, periodization, deload weeks, and cementing fitness as an unbreakable lifestyle.',
      weeks_start: 17,
      weeks_end: 24,
      days: phase3Days.map((d) => ({ ...d, id: d.id.replace('p3_', 'p4_'), phase: 4 as const })),
    },
  ],
};

// ─── Warm-Up Sequence (used before every workout session) ────────────────────

export const WARMUP_EXERCISES: WorkoutDayExercise[] = [
  { exercise: EXERCISES.wu_jumping_jacks,    sets: 1, reps: 1, duration_sec: 45, rest_sec: 10, order: 1 },
  { exercise: EXERCISES.wu_arm_circles,       sets: 1, reps: 1, duration_sec: 30, rest_sec:  5, order: 2 },
  { exercise: EXERCISES.wu_leg_swings,        sets: 1, reps: 1, duration_sec: 30, rest_sec:  5, order: 3 },
  { exercise: EXERCISES.wu_hip_circles,       sets: 1, reps: 1, duration_sec: 30, rest_sec:  5, order: 4 },
  { exercise: EXERCISES.wu_high_knees_march,  sets: 1, reps: 1, duration_sec: 30, rest_sec:  5, order: 5 },
  { exercise: EXERCISES.wu_torso_rotation,    sets: 1, reps: 1, duration_sec: 30, rest_sec:  5, order: 6 },
  { exercise: EXERCISES.wu_wrist_ankle_circles, sets: 1, reps: 1, duration_sec: 30, rest_sec: 5, order: 7 },
];

// ─── Cool-Down & Stretch Sequence (used after every workout session) ──────────

export const COOLDOWN_EXERCISES: WorkoutDayExercise[] = [
  { exercise: EXERCISES.cd_childs_pose,             sets: 1, reps: 1, duration_sec: 45, rest_sec: 5, order: 1 },
  { exercise: EXERCISES.cd_standing_quad_stretch,   sets: 1, reps: 1, duration_sec: 45, rest_sec: 5, order: 2 },
  { exercise: EXERCISES.cd_hamstring_stretch,        sets: 1, reps: 1, duration_sec: 45, rest_sec: 5, order: 3 },
  { exercise: EXERCISES.cd_chest_stretch,            sets: 1, reps: 1, duration_sec: 30, rest_sec: 5, order: 4 },
  { exercise: EXERCISES.cd_shoulder_stretch,         sets: 1, reps: 1, duration_sec: 40, rest_sec: 5, order: 5 },
  { exercise: EXERCISES.cd_spinal_twist,             sets: 1, reps: 1, duration_sec: 45, rest_sec: 5, order: 6 },
  { exercise: EXERCISES.cd_cat_cow,                  sets: 1, reps: 1, duration_sec: 45, rest_sec: 5, order: 7 },
  { exercise: EXERCISES.cd_neck_stretch,             sets: 1, reps: 1, duration_sec: 40, rest_sec: 5, order: 8 },
];

// ─── Trainer Discipline Code ──────────────────────────────────────────────────

export const DISCIPLINE_CODE = [
  {
    id: 'morning_ritual',
    title: 'Morning Ritual (15 min)',
    description: 'Wake, hydrate 500ml water, 5 min breathing, set your intention for the day.',
    time: '06:00',
    icon: '🌅',
  },
  {
    id: 'sleep',
    title: 'Sleep by 10:30 PM',
    description: 'No screens after 9:30 PM. Sleep is when you actually build muscle and burn fat.',
    time: '22:30',
    icon: '🌙',
  },
  {
    id: 'meal_prep',
    title: 'Sunday Meal Prep',
    description: 'Cook grains, protein, and veggies for 3 days. Control your food, control your body.',
    time: '17:00',
    icon: '🍱',
  },
  {
    id: 'protein',
    title: 'Protein With Every Meal',
    description: 'No exceptions. Protein protects muscle while you lose fat.',
    icon: '💪',
  },
  {
    id: 'steps',
    title: '8,000 Steps Daily',
    description: 'Active lifestyle outside the gym. Steps burn fat without touching recovery.',
    icon: '👣',
  },
  {
    id: 'water',
    title: '3.5L Water Daily',
    description: 'Hydration controls hunger, performance, and fat metabolism.',
    icon: '💧',
  },
  {
    id: 'weekly_checkin',
    title: 'Weekly Check-In (Sunday AM)',
    description: 'Weigh-in, waist measurement, progress photo. Data is your mirror.',
    time: '08:00',
    icon: '📊',
  },
];

// ─── South Indian Meal Suggestions ───────────────────────────────────────────

export const MEAL_SUGGESTIONS: import('../types').MealSuggestion[] = [
  {
    name: 'Ragi Porridge with Banana',
    meal_type: 'breakfast',
    description: 'High-fiber, low-GI breakfast that keeps you full until noon.',
    ingredients: ['ragi flour 60g', 'low-fat milk 200ml', 'banana 1', 'honey 1 tsp'],
    calories: 310,
    protein: 12,
    carbs: 55,
    fat: 5,
    prep_time_min: 10,
    is_south_indian: true,
    tags: ['high-fiber', 'low-GI', 'calcium'],
  },
  {
    name: 'Egg White Omelette with Idli',
    meal_type: 'breakfast',
    description: 'Lean protein with traditional South Indian carbs.',
    ingredients: ['egg whites 4', 'mini idli 4', 'onion', 'tomato', 'curry leaves', 'coconut chutney 1 tbsp'],
    calories: 340,
    protein: 28,
    carbs: 42,
    fat: 6,
    prep_time_min: 15,
    is_south_indian: true,
    tags: ['high-protein', 'lean'],
  },
  {
    name: 'Chicken Kuzhambu with Brown Rice',
    meal_type: 'lunch',
    description: 'Lean chicken in a spiced tomato-tamarind gravy. Classic Tamil comfort.',
    ingredients: ['chicken breast 150g', 'brown rice 100g', 'tomato', 'tamarind', 'curry leaves', 'spices'],
    calories: 480,
    protein: 42,
    carbs: 52,
    fat: 10,
    prep_time_min: 30,
    is_south_indian: true,
    tags: ['high-protein', 'complex-carbs'],
  },
  {
    name: 'Sambar with Millets and Vegetables',
    meal_type: 'lunch',
    description: 'Protein-rich lentil soup with millet — an inflammation-fighting powerhouse.',
    ingredients: ['toor dal 80g', 'foxtail millet 80g', 'drumstick', 'tomato', 'sambar powder', 'tamarind'],
    calories: 420,
    protein: 20,
    carbs: 72,
    fat: 5,
    prep_time_min: 25,
    is_south_indian: true,
    tags: ['plant-protein', 'anti-inflammatory', 'fiber'],
  },
  {
    name: 'Grilled Fish Fry with Rasam',
    meal_type: 'dinner',
    description: 'Omega-3-rich fish with light pepper rasam for the evening.',
    ingredients: ['fish (seer/pomfret) 200g', 'rasam 1 bowl', 'lemon', 'ginger garlic', 'turmeric', 'chili'],
    calories: 380,
    protein: 45,
    carbs: 12,
    fat: 14,
    prep_time_min: 20,
    is_south_indian: true,
    tags: ['omega-3', 'lean', 'anti-inflammatory'],
  },
  {
    name: 'Paneer Tikka with Cucumber Raita',
    meal_type: 'dinner',
    description: 'Grilled cottage cheese for vegetarian high-protein evening meal.',
    ingredients: ['low-fat paneer 150g', 'hung curd 100g', 'cucumber', 'spices', 'mint'],
    calories: 350,
    protein: 28,
    carbs: 15,
    fat: 18,
    prep_time_min: 25,
    is_south_indian: false,
    tags: ['vegetarian', 'high-protein'],
  },
  {
    name: 'Boiled Peanuts & Fruit Bowl',
    meal_type: 'snack',
    description: 'Mid-day protein and micronutrient boost.',
    ingredients: ['boiled peanuts 30g', 'papaya 100g', 'watermelon 100g'],
    calories: 210,
    protein: 8,
    carbs: 28,
    fat: 8,
    prep_time_min: 5,
    is_south_indian: true,
    tags: ['snack', 'fiber', 'vitamins'],
  },
  {
    name: 'Whey Protein with Coconut Water',
    meal_type: 'snack',
    description: 'Post-workout recovery — protein + electrolytes.',
    ingredients: ['whey protein 30g', 'coconut water 400ml'],
    calories: 195,
    protein: 26,
    carbs: 18,
    fat: 2,
    prep_time_min: 2,
    is_south_indian: false,
    tags: ['post-workout', 'recovery'],
  },
];

// ─── Meditation Progression ────────────────────────────────────────────────────

export const MEDITATION_PROGRAM = [
  {
    week_start: 1,
    week_end: 4,
    name: 'Introduction to Breath',
    technique: 'Box Breathing',
    duration_min: 5,
    description: 'You don\'t need to empty your mind. Just watch your breath. That\'s the whole practice.',
    instructions: [
      'Sit with your spine tall — chair or floor, doesn\'t matter',
      'Inhale slowly through your nose: 1-2-3-4',
      'Hold at the top: 1-2-3-4',
      'Exhale through your mouth: 1-2-3-4',
      'Hold empty: 1-2-3-4',
      'That\'s one round. Do 10 rounds.',
      'When thoughts come, notice them and return to counting. That IS the practice.',
    ],
  },
  {
    week_start: 5,
    week_end: 8,
    name: 'Body Scan Awareness',
    technique: 'Vipassana Body Scan',
    duration_min: 10,
    description: 'The body holds stress you\'re not even aware of. This practice finds it and releases it.',
    instructions: [
      'Lie down or sit comfortably, eyes closed',
      'Start at the crown of your head',
      'Slowly move attention down — forehead, jaw, neck, shoulders...',
      'Notice any tension without trying to change it',
      'Breathe into tense areas gently',
      'Continue all the way to your feet',
      'Spend 20-30 seconds at each area',
    ],
  },
  {
    week_start: 9,
    week_end: 16,
    name: 'Loving Kindness (Metta)',
    technique: 'Metta Bhavana',
    duration_min: 15,
    description: 'This practice rewires your brain\'s response to stress. It is the foundation of discipline without self-punishment.',
    instructions: [
      'Sit comfortably. Begin with box breathing for 2 minutes',
      'Bring to mind an image of yourself',
      'Silently repeat: "May I be well. May I be happy. May I be at peace."',
      'Feel it — don\'t just say the words',
      'Expand to someone you love. Same phrases.',
      'Expand to someone neutral.',
      'Expand to all beings.',
      'Sit with the warmth for a few minutes before opening your eyes.',
    ],
  },
  {
    week_start: 17,
    week_end: 24,
    name: 'Open Awareness',
    technique: 'Choiceless Awareness',
    duration_min: 20,
    description: 'No technique. Just presence. You\'ve built the foundation — now simply be.',
    instructions: [
      'Sit comfortably, no particular focus',
      'Let your attention rest where it naturally goes',
      'Sounds, sensations, thoughts — observe them as they arise and pass',
      'Don\'t hold anything. Don\'t push anything away.',
      'When you realize you\'ve been lost in thought, that moment of noticing IS awareness.',
      'That\'s all. That\'s everything.',
    ],
  },
];
